input_bag: /media/sgarimella34/hercules-collect/hercules-datasets/ausenv_test1_checkpoints_CSLAM_2UAVUGV
output_bag: /media/sgarimella34/hercules-collect/hercules-datasets/ausenv_test1_checkpoints_CSLAM_Husky1
external_msgs_path_ros2: /home/sgarimella34/multi-robot-coordination/rosbag_manip/external_msgs_ros2
external_msgs_path_ros1: /home/sgarimella34/multi-robot-coordination/rosbag_manip/external_msgs_ros1
operation_to_run: 'downsample'
operation_params:
  downsample:
    topics: 
      /clock: 1.0
      /events/read_split: 1.0 
      /events/write_split: 1.0 
      /hercules_node/Husky1/front_center_DepthPlanar/camera_info: 1.0 
      /hercules_node/Husky1/front_center_DepthPlanar/image: 1.0 
      /hercules_node/Husky1/front_center_Scene/camera_info: 1.0 
      /hercules_node/Husky1/front_center_Scene/image: 1.0 
      /hercules_node/Husky1/front_center_Segmentation/camera_info: 1.0 
      /hercules_node/Husky1/front_center_Segmentation/image: 1.0 
      /hercules_node/Husky1/global_gps: 1.0 
      /hercules_node/Husky1/ground_truth/odom_local: 1.0 
      /hercules_node/Husky1/imu/imu: 1.0 
      /hercules_node/Husky1/lidar/labels/LidarSensor1: 1.0 
      /hercules_node/Husky1/lidar/points/LidarSensor1: 1.0 
      /hercules_node/Husky1/magnetometer/magnetometer: 1.0 
      /hercules_node/instance_segmentation_labels: 1.0 
      /hercules_node/object_transforms: 1.0 
      /hercules_node/origin_geo_point: 1.0 
      /parameter_events: 1.0 
      /rosout: 1.0 
      /tf: 1.0 
      /tf_static: 1.0 
    include_unmentioned_topics: False